tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "elixir"
brew "fish"
brew "gnu-tar"
brew "gnupg"
brew "node"
brew "nomad"
brew "postgresql", restart_service: true
brew "postgis"
brew "terraform"
brew "yarn", link: false
